### ISSUE TITLE
1.0.0-prerelease not satisfied

### ISSUE THREAD

**Issue by zulli73** [podhmo/python-node-semver#37]
# max_satisfying possibly misbehaves
Requiring version `1.x`, max_satisfying does not return `1.0.0-alpha`. But it properly does so for `1.0.1-alpha`.

I suspect this to be a bug unless it is this some kind of semver.org feature I'm not yet aware of.

## Reproduce

```(py)
from semver import max_satisfying

range_ = '1.x'

print('Oooops:', max_satisfying(['1.0.0-alpha'], range_, loose=False, include_prerelease=True))
# BUT...
print('But:', max_satisfying(['1.0.1-alpha'], range_, loose=False, include_prerelease=True))
```
See also: https://repl.it/@RaphaelZulliger/NodeSemVermaxsatisfying

**Comment by raphaelzulliger** [comment]
Here are the tests, all part of [podhmo/python-semver/pull/40], that currently do not behave as I'd expect:

```
versions = ['1.0.0-beta'], range_ = '1.x', expect = '1.0.0-beta', loose = False, include_prerelease = True
E           AssertionError: assert None == '1.0.0-beta'
```

```
versions = ['1.1.0-beta'], range_ = '1.0.x', expect = None, loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == None
```

```
versions = ['1.0.0-beta', '1.1.0-beta', '1.1.0'], range_ = '1.0.x', expect = '1.0.0-beta', loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == '1.0.0-beta'
```

```
versions = ['1.0.0-beta', '1.0.0', '1.0.1-beta', '1.0.2-beta'], range_ = '>1.0.0 <1.0.2', expect = '1.0.1-beta', loose = False, include_prerelease = True
E           AssertionError: assert '1.0.2-beta' == '1.0.1-beta'
```

```
versions = ['1.0.0-beta', '1.0.0', '1.0.1', '1.1.0-beta', '1.1.0'], range_ = '>1.0.0 <1.1.0', expect = '1.0.1', loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == '1.0.1'
```

```
versions = ['1.0.0-beta', '1.1.0-beta'], range_ = '>1.0.0 <1.1.0', expect = None, loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == None
```

```
versions = ['1.0.0-beta', '1.0.0', '1.0.1', '1.1.0-beta'], range_ = '>=1.0.0 <1.1.0', expect = '1.0.1', loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == '1.0.1'
```

```
versions = ['1.0.0-beta', '1.1.0-beta'], range_ = '>=1.0.0-0 <1.1.0', expect = '1.0.0-beta', loose = False, include_prerelease = True
E           AssertionError: assert '1.1.0-beta' == '1.0.0-beta'
```

```
versions = ['1.0.0-pre'], range_ = '1.0.x', expect = '1.0.0-pre', loose = False, include_prerelease = True
E           AssertionError: assert None == '1.0.0-pre'
```

```
versions = ['1.0.0-pre'], range_ = '>=1.0.x', expect = '1.0.0-pre', loose = False, include_prerelease = True
E           AssertionError: assert None == '1.0.0-pre'
```

**Comment by Tomeamis** [comment]
Honestly, I think that this is correct behavior according to semver spec. `1.x` is supposed to be `>=1.0.0 <2.0.0`, and pre-release versions are defined in the semver spec to be *less* than the non-pre-release version. Therefore `1.0.0-alpha` is less than `1.0.0` and it is correct that it does not satisfy `1.x`.

**Comment by raphaelzulliger** [comment]
I thought about it again and I think I see your point. You may indeed be right, that this lib acts according to semver.

(More a semver-discussion then, but): From a user point of view, this seems strange - if not unusable. Assume the following

- `1.0.1` has been released and is in use
  - It's consumed by some projects specifying `1.x, include_prerelease=True`
- API breaking change happens -> I bump version to `2.0.0`
  - Since I just working on `2.0.0`, I add a pre-release tag: `2.0.0-alpha`
  - I upload my package to Conan Artifactory

=> Ooops: The consumers using `1.x, include_prerelease=True` will get `2.0.0-alpha` which contains API changes

```python
from semver import max_satisfying
range = '1.x'
print('Ooops: ', range, ' -> ', max_satisfying(['1.0.1', '2.0.0-alpha'], range, loose=False, include_prerelease=True))
```
```shell
Ooops:  1.x  ->  2.0.0-alpha
```

How to solve that?

I could *not* specify `include_prerelease=True`, then `1.x` would *not* find `2.0.0-alpha`. But it would also not find `1.0.2-rc1`

Any hint on that? Am I overlooking something here?

**Comment by Tomeamis** [comment]
I see your point. I guess that in this case it should indeed expand to `>=1.0.0-anyPrerelease <2.0.0-anyPrerelease`.

**Comment by raphaelzulliger** [comment]
I'm fine if you close this issue - since it seems out of scope of this library. Thanks and sorry for having claimed your time on this.
