### ISSUE TITLE
💣 Update Major version (but 0.9.0)

### ISSUE THREAD

**Issue by podhmo** [podhmo/python-node-semver#45]
include

- #40 
- rename module semver -> nodesemver #39

**Comment by podhmo** [comment]
#39 is huge change. 

before

```py
import semver
```

after

```py
import nodesemver
```

**Comment by podhmo** [comment]
please if caught a trouble after updated, pin version at 0.8.1.

**Comment by podhmo** [comment]
0.9.0-rc1 is released. (As it is for a while. maybe 2 months ?)

**Comment by tomschr** [comment]
Are there any news? :slightly_smiling_face: 

I'm just asking as the project python-semver and python-node-semver can't be used in the same Python virtual env at the same time. I'm sorry for all the hassles, but our users are still affected by this problem. Having a new release would probably mitigate it.

Many thanks for all your efforts! Much appreciated!

**Comment by podhmo** [comment]
oh, I forgot it, sorry.

**Comment by podhmo** [comment]
released it https://pypi.org/manage/project/node-semver/release/0.9.0/

**Comment by tomschr** [comment]
Thank you very much @podhmo!

However, the README still mentions `semver` instead of `nodesemver`. :wink:
