### ISSUE TITLE
Git tag for 0.8.1 is missing

### ISSUE THREAD

**Issue by mgorny** [podhmo/python-node-semver#50]
Please push the tag corresponding to the 0.8.1 release. We need it to package it for Gentoo.

**Comment by tivek** [comment]
Thank you @mgorny for opening this issue. We also need this tag to properly package it for Arch on AUR.

**Comment by podhmo** [comment]
ok. i will do later.

**Comment by podhmo** [comment]
added

**Comment by mgorny** [comment]
Thank you!
